# Generated by Django 5.1 on 2024-09-01 23:35

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='The name of the task', max_length=60, verbose_name='Task Name')),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today, help_text='The date the task was performed.', validators=[django.core.validators.MinValueValidator(datetime.date(2024, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2024, 12, 31))], verbose_name='Date')),
                ('hours', models.FloatField(default=0, help_text='The hours worked on this task/day', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='Hours')),
                ('user', models.ForeignKey(help_text='The user who performed the task', on_delete=django.db.models.deletion.CASCADE, related_name='hours_worked', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
