# Generated by Django 5.1.1 on 2024-10-14 19:08

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The English name of the task', max_length=60, unique=True, verbose_name='Task Name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today, help_text='The date the task was performed.', validators=[django.core.validators.MinValueValidator(datetime.date(2024, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2024, 10, 14))], verbose_name='Date')),
                ('hours', models.FloatField(default=0, help_text='The hours worked on this task/day', validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(24)], verbose_name='Hours')),
                ('user', models.ForeignKey(help_text='The user who performed the task', on_delete=django.db.models.deletion.CASCADE, related_name='hours_worked', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('task', models.ForeignKey(help_text='The task performed', on_delete=django.db.models.deletion.CASCADE, related_name='hours_worked', to='hours.task', verbose_name='Task')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TaskTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the task', max_length=60, verbose_name='Task Name')),
                ('language', models.ForeignKey(help_text='Task name language', on_delete=django.db.models.deletion.CASCADE, to='hours.language', verbose_name='Language')),
                ('task', models.ForeignKey(help_text='The task for translation', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hours.task', verbose_name='Task')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(models.F('name'), models.F('language'), name='name_unique_for_language')],
            },
        ),
    ]
