# Generated by Django 5.1 on 2024-10-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktranslation',
            name='language',
            field=models.CharField(help_text='Task name language', max_length=5, verbose_name='Language'),
        ),
    ]
