# Generated by Django 5.1.1 on 2024-10-18 23:27

import datetime
import django.core.validators
import hours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='date',
            field=models.DateField(default=datetime.datetime.today, help_text='The date the task was performed.', validators=[django.core.validators.MinValueValidator(hours.models.first_of_year), django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Date'),
        ),
    ]
