# Generated by Django 5.1.4 on 2024-12-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hours',
            name='comment',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='us_citizen',
            field=models.BooleanField(default=False, help_text='Check this box if you are a U.S Citizen or have a Green Card'),
        ),
    ]
