# Generated by Django 5.1 on 2024-10-11 21:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0003_alter_hours_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='date',
            field=models.DateField(default=datetime.datetime.today, help_text='The date the task was performed.', validators=[django.core.validators.MinValueValidator(datetime.date(2024, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2024, 10, 11))], verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='hours',
            name='hours',
            field=models.FloatField(default=0, help_text='The hours worked on this task/day', validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(24)], verbose_name='Hours'),
        ),
    ]
