# Generated by Django 5.1.4 on 2025-01-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0004_hours_comment_alter_profile_us_citizen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
