# Generated by Django 5.1.5 on 2025-02-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0005_alter_hours_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='help_emailed',
            field=models.CharField(default='N', help_text='Was the instructional email sent to this user?', max_length=1),
        ),
    ]
